name: Update folders.json

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'data_*/**'
      - 'data/**'
      - 'adult/**'
      - 'Adult/**'

  # Allow manual trigger
  workflow_dispatch:

jobs:
  update-manifest:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate folders.json
        run: |
          echo "Scanning for data folders..."

          # Find all folders matching data_* pattern in root and subdirectories
          # Supports both old format (data_YYYYMMDD_HHMM_CODE) and new format (data_YYYY-MM-DDTHH-MM_CODE)

          echo '{"folders":[' > folders.json

          first=true

          # Find timestamped data folders (search up to 3 levels deep)
          for dir in $(find . -maxdepth 3 -type d -name "data_*" | sort -r); do
            folder_name=$(basename "$dir")
            dir_path="${dir#./}"

            # Check if folder has stints.csv (valid data folder)
            if [ ! -f "$dir/stints.csv" ]; then
              continue
            fi

            timestamp=""
            code_part=""

            # Try new ISO-like format first: data_YYYY-MM-DDTHH-MM_CODE
            if [[ $folder_name =~ ^data_([0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}-[0-9]{2})_(.+)$ ]]; then
              timestamp="${BASH_REMATCH[1]}"
              code_part="${BASH_REMATCH[2]}"
              echo "Found (new format): $dir_path"
            # Try old format: data_YYYYMMDD_HHMM_CODE
            elif [[ $folder_name =~ ^data_([0-9]{8})_([0-9]{4})_(.+)$ ]]; then
              date_part="${BASH_REMATCH[1]}"
              time_part="${BASH_REMATCH[2]}"
              code_part="${BASH_REMATCH[3]}"
              timestamp="${date_part}_${time_part}"
              echo "Found (old format): $dir_path"
            fi

            if [ -n "$timestamp" ] && [ -n "$code_part" ]; then
              if [ "$first" = true ]; then
                first=false
              else
                echo ',' >> folders.json
              fi

              echo "  {\"path\":\"$dir_path\",\"folder_name\":\"$folder_name\",\"timestamp\":\"$timestamp\",\"competition_code\":\"$code_part\"}" >> folders.json
            fi
          done

          # Check for legacy 'data' folder
          if [ -d "./data" ] && [ -f "./data/stints.csv" ]; then
            if [ "$first" = true ]; then
              first=false
            else
              echo ',' >> folders.json
            fi
            echo '  {"path":"data","folder_name":"data","timestamp":"legacy","competition_code":"DEFAULT"}' >> folders.json
            echo "Found: legacy data folder"
          fi

          echo '' >> folders.json
          echo ']}' >> folders.json

          echo "Generated folders.json:"
          cat folders.json

      - name: Commit and push if changed
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add folders.json
          git diff --staged --quiet || git commit -m "Auto-update folders.json"
          git push
